// Chinese display names for ATC conditions.
// keyword -> { name_cn, description_cn }

module.exports = {
  diabetes: { name_cn: '2型糖尿病', desc_cn: '以血糖升高为特征的慢性代谢性疾病' },
  obesity: { name_cn: '肥胖症', desc_cn: '体脂过度积累导致的慢性代谢性疾病' },
  thyroid: { name_cn: '甲状腺功能减退', desc_cn: '甲状腺激素分泌不足的内分泌疾病' },
  cholesterol: { name_cn: '高脂血症', desc_cn: '血脂水平异常升高的代谢性疾病' },
  hypertension: { name_cn: '原发性高血压', desc_cn: '动脉血压持续升高的慢性心血管疾病' },
  heart: { name_cn: '心血管支持', desc_cn: '维持心脏与血管健康的综合支持' },
  arthritis: { name_cn: '骨关节炎', desc_cn: '关节软骨退行性病变导致的慢性关节疾病' },
  osteoporosis: { name_cn: '骨质疏松症', desc_cn: '骨密度降低、骨微结构破坏的代谢性骨病' },
  'joint pain': { name_cn: '关节痛', desc_cn: '关节区域的疼痛症状，可由多种原因引起' },
  muscle: { name_cn: '肌肉恢复/肌少症', desc_cn: '运动后肌肉修复或年龄相关的肌肉流失' },
  insomnia: { name_cn: '原发性失眠', desc_cn: '难以入睡或维持睡眠的睡眠障碍' },
  anxiety: { name_cn: '广泛性焦虑障碍', desc_cn: '持续性过度担忧和紧张的精神健康问题' },
  depression: { name_cn: '重度抑郁障碍', desc_cn: '以持续情绪低落和兴趣丧失为特征的心境障碍' },
  headache: { name_cn: '偏头痛/紧张性头痛', desc_cn: '反复发作的中重度头痛，常伴恶心畏光' },
  cognitive: { name_cn: '年龄相关认知衰退', desc_cn: '随年龄增长出现的记忆力与认知功能下降' },
  adhd: { name_cn: '注意力缺陷多动障碍', desc_cn: '以注意力不集中、多动冲动为特征的神经发育障碍' },
  neuropathy: { name_cn: '周围神经病变', desc_cn: '周围神经系统损伤导致的感觉和运动障碍' },
  constipation: { name_cn: '慢性便秘', desc_cn: '排便困难或排便频率显著减少的消化系统问题' },
  ibs: { name_cn: '肠易激综合征', desc_cn: '以腹痛、腹胀和排便习惯改变为特征的功能性肠病' },
  gerd: { name_cn: '胃食管反流病', desc_cn: '胃内容物反流至食管引起的消化系统疾病' },
  liver: { name_cn: '肝脏支持/解毒', desc_cn: '维护肝脏功能和促进体内毒素代谢的综合支持' },
  allergy: { name_cn: '过敏性鼻炎', desc_cn: '接触过敏原后由IgE介导的鼻黏膜炎症反应' },
  asthma: { name_cn: '支气管哮喘', desc_cn: '以气道慢性炎症和高反应性为特征的呼吸系统疾病' },
  acne: { name_cn: '寻常痤疮', desc_cn: '毛囊皮脂腺单位的慢性炎症性皮肤病' },
  eczema: { name_cn: '特应性皮炎/湿疹', desc_cn: '以皮肤干燥、瘙痒和反复发作为特征的慢性皮肤病' },
  psoriasis: { name_cn: '银屑病', desc_cn: '以皮肤红斑鳞屑为特征的慢性自身免疫性皮肤病' },
  'hair loss': { name_cn: '雄激素性脱发', desc_cn: '由遗传和雄激素因素导致的进行性毛发减少' },
  vision: { name_cn: '年龄相关性黄斑变性', desc_cn: '视网膜黄斑区退行性病变导致中心视力下降' },
  'dry eye': { name_cn: '干眼症', desc_cn: '泪液分泌不足或蒸发过快导致的眼表疾病' },
  menopause: { name_cn: '更年期症状', desc_cn: '女性卵巢功能衰退引起的一系列生理和心理症状' },
  pms: { name_cn: '经前期综合征', desc_cn: '月经前反复出现的躯体和情绪症状群' },
  bph: { name_cn: '良性前列腺增生', desc_cn: '前列腺非癌性增大导致的排尿功能障碍' },
  immune: { name_cn: '免疫支持', desc_cn: '增强机体免疫防御功能的综合营养支持' },
  fatigue: { name_cn: '慢性疲劳', desc_cn: '持续性极度疲劳，休息后不能缓解的复杂症状' },
  autoimmune: { name_cn: '自身免疫性疾病支持', desc_cn: '免疫系统攻击自身组织的疾病的辅助调理' },
};
