// Chinese display names for all nutrient elements.
// English canonical name -> Chinese display name.
// Used by seed/run.js to populate element_name_cn column.

module.exports = {
  // Vitamins
  'Vitamin A': '维生素A',
  'Vitamin B1 (Thiamin)': '维生素B1（硫胺素）',
  'Vitamin B2 (Riboflavin)': '维生素B2（核黄素）',
  'Vitamin B3 (Niacin)': '维生素B3（烟酸）',
  'Vitamin B5 (Pantothenic Acid)': '维生素B5（泛酸）',
  'Vitamin B6': '维生素B6',
  'Vitamin B7 (Biotin)': '维生素B7（生物素）',
  'Vitamin B9 (Folate)': '维生素B9（叶酸）',
  'Vitamin B12 (Cobalamin)': '维生素B12（钴胺素）',
  'Vitamin C': '维生素C',
  'Vitamin D3': '维生素D3',
  'Vitamin E': '维生素E',
  'Vitamin K1': '维生素K1',
  'Vitamin K2 (MK-7)': '维生素K2（MK-7）',
  'Choline': '胆碱',

  // Minerals
  'Calcium': '钙',
  'Magnesium': '镁',
  'Zinc': '锌',
  'Iron': '铁',
  'Selenium': '硒',
  'Copper': '铜',
  'Iodine': '碘',
  'Potassium': '钾',
  'Sodium': '钠',
  'Manganese': '锰',
  'Chromium': '铬',
  'Molybdenum': '钼',
  'Phosphorus': '磷',
  'Boron': '硼',
  'Silicon': '硅',

  // Amino Acids
  'L-Theanine': 'L-茶氨酸',
  'L-Arginine': 'L-精氨酸',
  'L-Lysine': 'L-赖氨酸',
  'L-Tryptophan': 'L-色氨酸',
  'L-Tyrosine': 'L-酪氨酸',
  'L-Carnitine': 'L-肉碱',
  'Taurine': '牛磺酸',
  'Glycine': '甘氨酸',
  'NAC (N-Acetyl Cysteine)': 'NAC（N-乙酰半胱氨酸）',
  'Glutamine': '谷氨酰胺',
  'Creatine': '肌酸',
  'BCAA': '支链氨基酸（BCAA）',
  'Beta-Alanine': 'β-丙氨酸',
  'Citrulline': '瓜氨酸',

  // Fatty Acids
  'Omega-3 (EPA+DHA)': 'Omega-3（EPA+DHA）',
  'Omega-6 (LA)': 'Omega-6（亚油酸）',
  'Omega-7': 'Omega-7',
  'Omega-9': 'Omega-9',
  'ALA (Alpha-Linolenic Acid)': 'ALA（α-亚麻酸）',
  'GLA (Gamma-Linolenic Acid)': 'GLA（γ-亚麻酸）',

  // Herbals / Adaptogens
  'Ashwagandha': '印度人参（南非醉茄）',
  'Maca Root': '玛卡根',
  'Rhodiola Rosea': '红景天',
  'Panax Ginseng': '人参',
  'Ginkgo Biloba': '银杏叶',
  'Turmeric (Curcumin)': '姜黄素',
  'Milk Thistle (Silymarin)': '奶蓟草（水飞蓟素）',
  'Echinacea': '紫锥菊',
  'Valerian Root': '缬草根',
  "St. John's Wort": '贯叶连翘（圣约翰草）',
  'Saw Palmetto': '锯棕榈',
  'Black Cohosh': '黑升麻',
  'Astragalus': '黄芪',
  'Holy Basil (Tulsi)': '圣罗勒',
  'Reishi Mushroom': '灵芝',
  "Lion's Mane": '猴头菇',
  'Cordyceps': '冬虫夏草',
  'Bacopa Monnieri': '假马齿苋（婆罗米）',
  'Fenugreek': '葫芦巴',
  'Tribulus Terrestris': '蒺藜',

  // Enzymes
  'Bromelain': '菠萝蛋白酶',
  'Papain': '木瓜蛋白酶',
  'Lactase': '乳糖酶',
  'Amylase': '淀粉酶',
  'Protease': '蛋白酶',

  // Probiotics
  'Probiotics': '益生菌',

  // Other
  'Coenzyme Q10 (CoQ10)': '辅酶Q10',
  'Melatonin': '褪黑素',
  'Glucosamine': '葡萄糖胺',
  'Chondroitin': '软骨素',
  'MSM (Methylsulfonylmethane)': 'MSM（二甲基砜）',
  'Collagen': '胶原蛋白',
  '5-HTP': '5-HTP（5-羟色氨酸）',
  'Alpha-Lipoic Acid': 'α-硫辛酸',
  'Resveratrol': '白藜芦醇',
  'Quercetin': '槲皮素',
  'Hyaluronic Acid': '透明质酸',
  'Lutein': '叶黄素',
  'Zeaxanthin': '玉米黄质',
  'Astaxanthin': '虾青素',
  'Beta-Carotene': 'β-胡萝卜素',
  'Spirulina': '螺旋藻',
  'Chlorella': '小球藻',
  'Wheatgrass': '小麦草',
  'Apple Cider Vinegar': '苹果醋',
  'GABA': 'GABA（γ-氨基丁酸）',
  'Inositol': '肌醇',
  'PQQ (Pyrroloquinoline Quinone)': 'PQQ（吡咯喹啉醌）',
  'D-Mannose': 'D-甘露糖',
  'Berberine': '小檗碱',
  'Whey Protein': '乳清蛋白',
  'Green Tea Extract': '绿茶提取物',
  'Inositol': '肌醇',
  'Phosphatidylserine': '磷脂酰丝氨酸',
};
